wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1633367659
    t:
      1:
      - 1
      4: 3.8.10
      5: 0.12.0
      8:
      - 5
batch_interval:
  desc: null
  value: -1
batch_size:
  desc: null
  value: 300
buffer_size:
  desc: null
  value: 100
buffer_size_debug:
  desc: null
  value: 100
debug:
  desc: null
  value: true
device:
  desc: null
  value: cuda:0
epoch_interval:
  desc: null
  value: 1
epochs:
  desc: null
  value: 10000
iter_per_epoch:
  desc: null
  value: 66
max_steps:
  desc: null
  value: 2000
num_envs:
  desc: null
  value: 10
optim_weights_directory:
  desc: null
  value: optim_weights
reg_lambda:
  desc: null
  value: 0.01
repeats_per_buffer:
  desc: null
  value: 5
scheduler_gamma:
  desc: null
  value: 0.5
scheduler_steps:
  desc: null
  value: 5
start_epoch:
  desc: null
  value: 0
starting_LR:
  desc: null
  value: 0.001
step_sched_num:
  desc: null
  value: 132000.0
tracknet_number:
  desc: null
  value: 0
tracknet_version:
  desc: null
  value: _7
transitions_per_epoch:
  desc: null
  value: 100
wandb:
  desc: null
  value: true
weights_directory:
  desc: null
  value: weights
